name: Main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        arch: ['linux/amd64', 'linux/arm64']
        os: ['ubuntu-22.04']
    with:
      runner-os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.arch }}-${{ github.ref_name }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.arch }}-${{ github.ref_name }}-
        ${{ matrix.os }}-buildx-${{ matrix.arch }}-
